events {}

http {
  upstream web_cluster {
    server web:5000;  # "web" resolve para todos os containers do serviço
  }

  server {
    listen 80;
    location / {
      proxy_pass       http://web_cluster;
      proxy_set_header Host $host;
    }
  }
}
